installbin renamed to installapp

diff --git a/Makefile.kics2 b/Makefile.kics2
--- a/Makefile.kics2
+++ b/Makefile.kics2
@@ -221,7 +221,7 @@ acy: $(LIB_ACY)
 .PHONY: checkcurrydoc
 checkcurrydoc:
 	@if [ ! -x "$(CURRYDOC)" ] ; then \
-	  echo "ERROR: Executable 'curry-doc' is not installed!" && echo "Install it by > cpm installbin currydoc" && exit 1 ; \
+	  echo "ERROR: Executable 'curry-doc' is not installed!" && echo "Install it by > cpm installapp currydoc" && exit 1 ; \
 	fi
 
 INDEXHTML    = $(LIBDOCDIR)/index.html
diff --git a/Makefile.pakcs b/Makefile.pakcs
--- a/Makefile.pakcs
+++ b/Makefile.pakcs
@@ -92,7 +92,7 @@ pl: .curry/pakcs/$(ALLLIBS).pl $(LIB_PL)
 .PHONY: checkcurrydoc
 checkcurrydoc:
 	@if [ ! -x "$(CURRYDOC)" ] ; then \
-	  echo "ERROR: Executable 'curry-doc' is not installed!" && echo "Install it by > cpm installbin currydoc" && exit 1 ; \
+	  echo "ERROR: Executable 'curry-doc' is not installed!" && echo "Install it by > cpm installapp currydoc" && exit 1 ; \
 	fi
 
 INDEXHTML    = $(LIBDOCDIR)/index.html
